import { StyleSheet } from 'react-native';

const styleButton = StyleSheet.create({
  button: {
    padding: 10,
    backgroundColor: '#8CDB94',
    borderColor: '#999',
    borderWidth: 1,
    borderRadius: 5,
    width: 300,
    margin: 10,
    marginTop: 20,
    color: '#8CDB94',
  },
  buttonBack: {
    backgroundColor: '#888888',
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#000',
    width: 100,
    margin: 70,
  },
  buttonBack2: {
    backgroundColor: '#888888',
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#000',
    width: 100,
    marginTop: 200,
  },
  buttonDeviceActivation: {
    backgroundColor: '#888888',
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#000',
    width: 100,
    marginTop: 200,
  },
  buttonDeviceOn: {
    backgroundColor: '#8CDB94',
    padding: 15,
    borderRadius: 100,
    borderLeftWidth: 5,
    borderLeftColor: '#2FA822',
    borderRightWidth: 1,
    borderRightColor: '#2FA822',
    borderBottomWidth: 5,
    borderBottomColor: '#2FA822',
    width: 80,
    margin: 80,
  },
  buttonDeviceOff: {
    backgroundColor: '#FD0201',
    padding: 15,
    borderRadius: 100,
    borderLeftWidth: 5,
    borderLeftColor: '#CF0100',
    borderRightWidth: 1,
    borderRightColor: '#CF0100',
    borderBottomWidth: 5,
    borderBottomColor: '#CF0100',
    width: 80,
    margin: 80,
  },
  buttonRegistryEntry: {
    width: 150,
    height: 220,
    backgroundColor: '#8CDB94',
    borderColor: '#999',
    borderWidth: 1,
    margin: 5,
    borderRadius: 5
  },
  buttonShowScreen: {
    marginTop: 25,
    backgroundColor: '#8CDB94',
    borderColor: '#999',
    borderWidth: 1,
    width: 280,
    height: 50,
    borderRadius: 5,
  }
});

export default styleButton;
